# Run pipeline automatically on main branch commits
trigger:
  branches:
    include:
      - main

# Run pipeline automatically for PRs into main
pr:
  branches:
    include:
      - main

# Allow manual runs from Azure DevOps
resources:
  pipelines: []

pool:
  name: Default   # self-hosted agent

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: npm install
    displayName: 'Install dependencies'

  - script: npm run cypress:report
    displayName: 'Run Cypress tests with reporters'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/cypress/reports/junit/test-results-*.xml'
      testRunTitle: 'Cypress Test Results'
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'cypress/reports/mochawesome'
      artifactName: 'MochawesomeReport'
    condition: always()

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'cypress/screenshots'
      artifactName: 'CypressScreenshots'
    condition: failed()

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'cypress/videos'
      artifactName: 'CypressVideos'
    condition: failed()
