trigger:
- main   # runs when you push to main branch (you can adjust this)

pool:
  name: Default   # your self-hosted agent pool name

steps:
  # Install Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  # Install dependencies
  - script: npm install
    displayName: 'Install dependencies'

  # Run Cypress with reporters (from package.json script)
  - script: npm run cypress:report
    displayName: 'Run Cypress tests with reporters'

  # ✅ Publish JUnit test results to Test Results tab
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/cypress/reports/junit/test-results-*.xml'
      testRunTitle: 'Cypress Test Results'
    condition: succeededOrFailed()

  # ✅ Publish Mochawesome HTML report as an artifact
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'cypress/reports/mochawesome'
      artifactName: 'MochawesomeReport'
    condition: always()

  # ✅ Publish Cypress screenshots (if tests fail)
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'cypress/screenshots'
      artifactName: 'CypressScreenshots'
    condition: failed()

  # ✅ Publish Cypress videos (if tests fail)
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'cypress/videos'
      artifactName: 'CypressVideos'
    condition: failed()
